/*
Simon Restrepo
Create the following table(s) as follows:
*/


CREATE TABLE EMPLOYEES(
  ID NUMBER(*,0),
  MANAGER_ID  NUMBER(*,0),
  DATE_OF_JOINING DATE NOT NULL,
  FULL_NAME VARCHAR2(255 BYTE) NOT NULL,
  CONSTRAINT EMPLOYEES_PK  PRIMARY KEY (ID)
);

CREATE TABLE PROJECTS(
  ID NUMBER(*,0),
  CODE VARCHAR2(255 BYTE) NOT NULL,
  MANAGER_ID NUMBER(*,0),
  BUDGET NUMBER(10,2) NOT NULL,
  DATE_OF_BEGINNING DATE,
  DATE_OF_ENDING DATE,
  CONSTRAINT PROJECTS_PK PRIMARY KEY (ID)
  -- CONSTRAINT FK_MANJER_PROJECT FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(MANAGER_ID)
);

CREATE TABLE SALARIES (
   ID NUMBER(*,0),
   EMPLOYEE_ID NUMBER(*,0) NOT NULL,
   PROJECT_ID NUMBER(*,0),
   SALARY NUMBER(10,2) NOT NULL,
   CONSTRAINT SALARIES_PK PRIMARY KEY (ID),
   CONSTRAINT FK_SALARY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID),
   CONSTRAINT FK_SALARY_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID),
   CONSTRAINT SALARY_GRATER_500 CHECK (SALARY >= 500)
);


SELECT * 
FROM EMPLOYEES e 
  inner join PROJECTS p ON e.
where e.ID = '44905736599';
  
